// Dashboard data layer.
//
// Loads the published VTI corpus (same source as the distribution endpoint) and
// derives the aggregations the dashboard shows: totals, severity + proof-method
// distributions, the class × SDK coverage matrix, and the recent-traps ledger.
// Fixture bodies are never included here — the dashboard is public (North Star
// #1), so only metadata + the proof receipt travel to the client.

import type { CorpusVti } from "./brainblast/corpus";
import { TRAP_CLASSES, type TrapClass } from "./brainblast/vtiClass";
import { loadVerifiedSubmissions } from "./submissions";
import { lotFor, type LotName } from "./vti";

// The seed lot is the live, always-current corpus (regenerated by gen:vti on every
// change). The versioned v0.1.0/full lot lags it — it's a pinned release snapshot.
// The public overview shows the current corpus, so it reads from seed.
const DEFAULT_SOURCE =
  "https://raw.githubusercontent.com/DSB-117/brainblast/main/datasets/seed/seed-vti.jsonl";

export interface LedgerRow {
  trapId: string;
  title: string;
  sdk: string;
  class: TrapClass;
  severity: CorpusVti["severity"];
  proofMethod: string;
  corroboration: number;
  capturedAt: string | null;
  lot: LotName; // which curated, sellable lot this VTI belongs to
}

export interface CoverageCell {
  class: TrapClass;
  sdk: string;
  count: number;
}

export interface Dashboard {
  totals: { vtis: number; sdks: number; classes: number; reproductionPct: number };
  severity: { critical: number; high: number; medium: number; low: number };
  proofMethods: { method: string; count: number }[];
  sdkCounts: { sdk: string; count: number }[];
  coverage: { classes: TrapClass[]; sdks: string[]; cells: CoverageCell[]; uncovered: TrapClass[] };
  ledger: LedgerRow[];
  generatedAt: string;
}

function proofMethodOf(v: CorpusVti): string {
  const m = (v.redGreenProof as { method?: string } | undefined)?.method;
  if (!m) return "static-checker";
  if (m.includes("differential") || m.includes("executed")) return "behavioral";
  if (m.includes("compile")) return "compiler";
  return "static-checker";
}

function shortSdk(name: string): string {
  return name
    .replace(/^@[^/]+\//, "")
    .replace(/ Node SDK| price feeds| Aggregator API| \(.*\)$| arithmetic/i, "")
    .trim();
}

export async function loadDashboard(): Promise<Dashboard> {
  const url = process.env.VTI_SOURCE_URL?.split(",")[0]?.trim() || DEFAULT_SOURCE;
  let records: CorpusVti[] = [];
  try {
    const res = await fetch(url, { next: { revalidate: 45 } });
    if (res.ok) {
      // Parse per line and SKIP any that don't parse — a single corrupt line
      // (e.g. a stray git conflict marker committed into the dataset) must never
      // zero the whole public dashboard. Degrade gracefully, not fail-closed.
      for (const line of (await res.text()).split("\n")) {
        const t = line.trim();
        if (!t) continue;
        try {
          records.push(JSON.parse(t) as CorpusVti);
        } catch {
          // skip the unparseable line
        }
      }
    }
  } catch {
    records = [];
  }

  // Fold in RED→GREEN-verified direct submissions (the /api/vti path) so an
  // API-landed VTI shows on the public dashboard with no PR. Deduped by trapId
  // below (a submission already promoted to the git corpus won't double-count).
  try {
    records.push(...(await loadVerifiedSubmissions()));
  } catch {
    // never let the submissions store take down the dashboard
  }

  // Dedupe by trapId. A trapId is unique in the corpus, so this is correct in the
  // normal case — and it also neutralizes a both-sides-present git merge conflict
  // (which would otherwise double-count every record) into the right number.
  const seenTrap = new Set<string>();
  records = records.filter((v) => {
    if (!v?.trapId || seenTrap.has(v.trapId)) return false;
    seenTrap.add(v.trapId);
    return true;
  });

  const severity = { critical: 0, high: 0, medium: 0, low: 0 };
  const proofCount = new Map<string, number>();
  const sdkTotal = new Map<string, number>();
  const cellMap = new Map<string, number>();
  const sdkSet = new Set<string>();
  const classSet = new Set<string>();
  let proven = 0;

  const ledger: LedgerRow[] = [];

  for (const v of records) {
    severity[v.severity] = (severity[v.severity] ?? 0) + 1;
    const pm = proofMethodOf(v);
    proofCount.set(pm, (proofCount.get(pm) ?? 0) + 1);
    const sdk = shortSdk(v.sdk?.name ?? "unknown");
    sdkSet.add(sdk);
    classSet.add(v.class);
    sdkTotal.set(sdk, (sdkTotal.get(sdk) ?? 0) + 1);
    cellMap.set(`${v.class}|||${sdk}`, (cellMap.get(`${v.class}|||${sdk}`) ?? 0) + 1);
    const isProven = v.redGreenProof?.red === true && v.redGreenProof?.green === true;
    if (isProven) proven++;

    ledger.push({
      trapId: v.trapId,
      title: (v.title as string) ?? v.trapId,
      sdk,
      class: v.class,
      severity: v.severity,
      proofMethod: pm,
      corroboration: Math.max(0, v.corroborationCount ?? 0),
      capturedAt: (v.capturedAt as string) ?? null,
      lot: lotFor(v),
    });
  }

  ledger.sort((a, b) => (b.capturedAt ?? "").localeCompare(a.capturedAt ?? ""));

  const sdks = [...sdkSet].sort((a, b) => (sdkTotal.get(b) ?? 0) - (sdkTotal.get(a) ?? 0));
  const usedClasses = TRAP_CLASSES.filter((c) => classSet.has(c));
  const cells: CoverageCell[] = [];
  for (const [k, count] of cellMap) {
    const [cls, sdk] = k.split("|||");
    cells.push({ class: cls as TrapClass, sdk, count });
  }
  const uncovered = TRAP_CLASSES.filter((c) => !classSet.has(c));

  return {
    totals: {
      vtis: records.length,
      sdks: sdkSet.size,
      classes: classSet.size,
      reproductionPct: records.length ? Math.round((proven / records.length) * 100) : 100,
    },
    severity,
    proofMethods: [...proofCount.entries()]
      .map(([method, count]) => ({ method, count }))
      .sort((a, b) => b.count - a.count),
    sdkCounts: sdks.map((sdk) => ({ sdk, count: sdkTotal.get(sdk) ?? 0 })),
    coverage: { classes: usedClasses, sdks, cells, uncovered },
    ledger,
    generatedAt: new Date().toISOString(),
  };
}
